volumes:
  serasa_postgres_data:

networks:
  serasa-network:
    driver: bridge

services:
  api:
    image: devgustavovasquez/challenge-serasa:latest
    container_name: serasa_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public
    ports:
      - ${PORT}:${PORT}
    networks:
      - serasa-network
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: serasa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5434:5432"
    volumes:
      - serasa_postgres_data:/var/lib/postgresql/data
    networks:
      - serasa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
